name: orchestrator_flutter
description: Flutter integrations for orchestrator_core. Provides default OfflineStorage and Connectivity implementations.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  orchestrator_core:
    path: ../orchestrator_core
  
  # Offline Support Default Impl
  path_provider: ^2.0.0
  connectivity_plus: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
