name: orchestrator_flutter
description: >-
  Flutter platform implementations for orchestrator_core's offline support.
  Provides FileNetworkQueueStorage, FlutterFileSafetyDelegate, and FlutterConnectivityProvider.
version: 0.3.3
homepage: https://github.com/lploc94/flutter_orchestrator
repository: https://github.com/lploc94/flutter_orchestrator
issue_tracker: https://github.com/lploc94/flutter_orchestrator/issues
documentation: https://github.com/lploc94/flutter_orchestrator/blob/main/docs/en/README.md

topics:
  - offline
  - connectivity
  - storage
  - orchestrator
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  orchestrator_core: ^0.3.3
  
  # Offline Support Default Impl
  path_provider: ^2.0.0
  connectivity_plus: ">=5.0.0 <8.0.0"
  path: ^1.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


