name: orchestrator_generator
description: Code generator for orchestrator_core's Offline Support.
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.0.0

dependencies:
  build: ^2.4.0
  source_gen: ^1.4.0
  analyzer: ^6.0.0
  code_builder: ^4.5.0
  dart_style: ^2.3.0
  orchestrator_core:
    path: ../orchestrator_core

dev_dependencies:
  test: ^1.24.0
