name: Publish to pub.dev

on:
  release:
    types: [published]

jobs:
  publish-core:
    name: Publish orchestrator_core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      
      - name: Setup credentials
        run: |
          mkdir -p $HOME/.config/dart
          echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.config/dart/pub-credentials.json
      
      - name: Publish
        working-directory: packages/orchestrator_core
        run: dart pub publish --force

  publish-bloc:
    name: Publish orchestrator_bloc
    needs: publish-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Setup credentials
        run: |
          mkdir -p $HOME/.config/dart
          echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.config/dart/pub-credentials.json
      
      - name: Publish
        working-directory: packages/orchestrator_bloc
        run: flutter pub publish --force

  publish-provider:
    name: Publish orchestrator_provider
    needs: publish-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Setup credentials
        run: |
          mkdir -p $HOME/.config/dart
          echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.config/dart/pub-credentials.json
      
      - name: Publish
        working-directory: packages/orchestrator_provider
        run: flutter pub publish --force

  publish-riverpod:
    name: Publish orchestrator_riverpod
    needs: publish-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - name: Setup credentials
        run: |
          mkdir -p $HOME/.config/dart
          echo '${{ secrets.PUB_CREDENTIALS }}' > $HOME/.config/dart/pub-credentials.json
      
      - name: Publish
        working-directory: packages/orchestrator_riverpod
        run: flutter pub publish --force
